# Module manifest for module 'PowerShell-Core-Compatibility-Alias'
# Generated by: Sascha Stumpler
# Generated on: 26.02.2018

@{
    RootModule        = 'PSHVTag.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = 'd889f708-47f3-424e-b7fb-75d8b50f6219'
    Author            = 'Sascha Stumpler'
    CompanyName       = 'Unknown'
    Copyright         = '(c) Sascha Stumpler. All rights reserved.'
    Description       = ''
    FunctionsToExport = @()
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            # LicenseUri = ''
            # ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}

